"""run outcome payload

Revision ID: 61162a63a8b7
Revises: c1b21fc1d09b
Create Date: 2026-07-26 14:47:50.753313

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "61162a63a8b7"
down_revision: str | Sequence[str] | None = "c1b21fc1d09b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema.

    Autogenerated, then corrected by hand: alembic rendered the server default
    as the string `{}'::jsonb`, having dropped its opening quote, which DDL
    would have taken as a text literal rather than an empty JSONB object.
    `sa.text` says what is meant without depending on that quoting.
    """
    op.add_column(
        "runs",
        sa.Column(
            "outcome",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("runs", "outcome")
    # ### end Alembic commands ###
