"""spans table

Revision ID: 7f69d654ed1c
Revises: 54c5477e4c0f
Create Date: 2026-07-27 15:09:23.883561

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7f69d654ed1c"
down_revision: str | Sequence[str] | None = "54c5477e4c0f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema.

    Autogenerated; the JSONB default is written with `sa.text` for the reason
    revision 61162a63a8b7 records — alembic renders it as a bare string whose
    opening quote has been dropped, which DDL takes as a text literal rather
    than an empty JSONB object.

    A plain table rather than a hypertable, unlike `observations`: a
    single-user workbench produces spans in the thousands, not the millions.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "spans",
        sa.Column("trace_id", sa.String(length=32), nullable=False),
        sa.Column("span_id", sa.String(length=16), nullable=False),
        sa.Column("parent_span_id", sa.String(length=16), nullable=True),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("kind", sa.String(length=20), nullable=False),
        sa.Column("status", sa.String(length=10), nullable=False),
        sa.Column("detail", sa.Text(), server_default="", nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("duration_ms", sa.Float(), nullable=False),
        sa.Column(
            "attributes",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.CheckConstraint("status IN ('ok', 'error', 'unset')", name="ck_spans_status_known"),
        sa.CheckConstraint("duration_ms >= 0", name="ck_spans_duration_non_negative"),
        sa.CheckConstraint(
            "parent_span_id IS NULL OR parent_span_id <> span_id", name="ck_spans_no_self_parent"
        ),
        sa.PrimaryKeyConstraint("trace_id", "span_id"),
    )
    op.create_index(op.f("ix_spans_name"), "spans", ["name"], unique=False)
    op.create_index(op.f("ix_spans_started_at"), "spans", ["started_at"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_spans_started_at"), table_name="spans")
    op.drop_index(op.f("ix_spans_name"), table_name="spans")
    op.drop_table("spans")
    # ### end Alembic commands ###
