"""project mcp servers and allowlist

Revision ID: a9548788149c
Revises: ea19a527e8dd
Create Date: 2026-07-27 16:52:54.658956

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a9548788149c"
down_revision: str | Sequence[str] | None = "ea19a527e8dd"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema.

    The JSONB defaults are written with `sa.text` for the reason revision
    61162a63a8b7 records: alembic renders them as bare strings whose opening
    quote has been dropped, which DDL takes as text literals.

    Both default to empty, and that is the security property rather than a
    convenience — §9 has MCP off by default, and an absent allowlist must mean
    "nothing is permitted" rather than "everything is".
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "projects",
        sa.Column(
            "mcp_servers",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
    )
    op.add_column(
        "projects",
        sa.Column(
            "mcp_allowlist",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("projects", "mcp_allowlist")
    op.drop_column("projects", "mcp_servers")
    # ### end Alembic commands ###
