"""runs and steps

Revision ID: c1b21fc1d09b
Revises: d669e38d8749
Create Date: 2026-07-25 20:34:15.170307

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c1b21fc1d09b"
down_revision: str | Sequence[str] | None = "d669e38d8749"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "runs",
        sa.Column("chat_id", sa.Uuid(), nullable=False),
        sa.Column("question", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=20), server_default="running", nullable=False),
        sa.Column("tier", sa.String(length=20), server_default="critic", nullable=False),
        sa.Column("revisions", sa.Integer(), server_default="0", nullable=False),
        sa.Column("error", sa.Text(), server_default="", nullable=False),
        sa.Column("input_tokens", sa.Integer(), server_default="0", nullable=False),
        sa.Column("output_tokens", sa.Integer(), server_default="0", nullable=False),
        sa.Column("cache_read_tokens", sa.Integer(), server_default="0", nullable=False),
        sa.Column("cache_write_tokens", sa.Integer(), server_default="0", nullable=False),
        sa.Column("cost_usd", sa.Float(), server_default="0", nullable=False),
        sa.Column("latency_ms", sa.Float(), server_default="0", nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('running', 'completed', 'blocked', 'failed')", name="ck_runs_status_known"
        ),
        sa.CheckConstraint("tier IN ('single', 'critic', 'consensus')", name="ck_runs_tier_known"),
        sa.CheckConstraint("cost_usd >= 0", name="ck_runs_cost_non_negative"),
        sa.CheckConstraint(
            "input_tokens >= 0 AND output_tokens >= 0"
            " AND cache_read_tokens >= 0 AND cache_write_tokens >= 0",
            name="ck_runs_tokens_non_negative",
        ),
        sa.CheckConstraint("length(trim(question)) > 0", name="ck_runs_question_not_blank"),
        sa.CheckConstraint("revisions >= 0", name="ck_runs_revisions_non_negative"),
        sa.ForeignKeyConstraint(["chat_id"], ["chats.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_runs_chat_id"), "runs", ["chat_id"], unique=False)
    op.create_table(
        "run_steps",
        sa.Column("seq", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("run_id", sa.Uuid(), nullable=False),
        sa.Column("parent_id", sa.Uuid(), nullable=True),
        sa.Column("agent", sa.String(length=30), nullable=False),
        sa.Column("kind", sa.String(length=10), nullable=False),
        sa.Column("status", sa.String(length=10), nullable=False),
        sa.Column("attempt", sa.Integer(), server_default="1", nullable=False),
        sa.Column("provider", sa.String(length=50), nullable=True),
        sa.Column("model", sa.String(length=200), nullable=True),
        sa.Column("input_tokens", sa.Integer(), server_default="0", nullable=False),
        sa.Column("output_tokens", sa.Integer(), server_default="0", nullable=False),
        sa.Column("cache_read_tokens", sa.Integer(), server_default="0", nullable=False),
        sa.Column("cache_write_tokens", sa.Integer(), server_default="0", nullable=False),
        sa.Column("cost_usd", sa.Float(), server_default="0", nullable=False),
        sa.Column("latency_ms", sa.Float(), server_default="0", nullable=False),
        sa.Column("tool", sa.String(length=100), nullable=True),
        sa.Column("tool_call_hash", sa.String(length=64), nullable=True),
        sa.Column("detail", sa.Text(), server_default="", nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "agent IN ('planner', 'data_steward', 'econometrician', 'validator', 'narrator')",
            name="ck_run_steps_agent_known",
        ),
        sa.CheckConstraint("kind IN ('llm', 'tool')", name="ck_run_steps_kind_known"),
        sa.CheckConstraint(
            "status IN ('ok', 'refused', 'failed', 'skipped')", name="ck_run_steps_status_known"
        ),
        sa.CheckConstraint("attempt >= 1", name="ck_run_steps_attempt_positive"),
        sa.CheckConstraint("cost_usd >= 0", name="ck_run_steps_cost_non_negative"),
        sa.CheckConstraint(
            "input_tokens >= 0 AND output_tokens >= 0"
            " AND cache_read_tokens >= 0 AND cache_write_tokens >= 0",
            name="ck_run_steps_tokens_non_negative",
        ),
        sa.CheckConstraint(
            "parent_id IS NULL OR parent_id <> id", name="ck_run_steps_no_self_parent"
        ),
        sa.ForeignKeyConstraint(["parent_id"], ["run_steps.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["run_id"], ["runs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_run_steps_parent_id"), "run_steps", ["parent_id"], unique=False)
    op.create_index(op.f("ix_run_steps_run_id"), "run_steps", ["run_id"], unique=False)
    op.create_index(op.f("ix_run_steps_seq"), "run_steps", ["seq"], unique=True)
    op.create_index(
        op.f("ix_run_steps_tool_call_hash"), "run_steps", ["tool_call_hash"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_run_steps_tool_call_hash"), table_name="run_steps")
    op.drop_index(op.f("ix_run_steps_seq"), table_name="run_steps")
    op.drop_index(op.f("ix_run_steps_run_id"), table_name="run_steps")
    op.drop_index(op.f("ix_run_steps_parent_id"), table_name="run_steps")
    op.drop_table("run_steps")
    op.drop_index(op.f("ix_runs_chat_id"), table_name="runs")
    op.drop_table("runs")
    # ### end Alembic commands ###
