"""step prompt and response

Revision ID: ea19a527e8dd
Revises: 7f69d654ed1c
Create Date: 2026-07-27 15:56:32.624553

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ea19a527e8dd"
down_revision: str | Sequence[str] | None = "7f69d654ed1c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("run_steps", sa.Column("prompt", sa.Text(), server_default="", nullable=False))
    op.add_column("run_steps", sa.Column("response", sa.Text(), server_default="", nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("run_steps", "response")
    op.drop_column("run_steps", "prompt")
    # ### end Alembic commands ###
